
server:
  port: 8088

spring:
  profiles:
    active: local
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid:
      #初始化连接大小
      initialSize: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      filters: stat,config
  flyway:
    clean-disabled: true
    baseline-on-migrate: true

property:
  jwt:
    header: Authorization
    secret: mySecret
    expiration: 10
    tokenHead: Bearer
    route:
      authentication:
        login: "auth/login"
        refresh: "auth/refresh"
        register: "auth/register"
  cors:
    enabled: true
    allowed-origins:
      - "*"
    allowed-methods:
      - "POST"
      - "GET"
      - "DELETE"
      - "PUT"
logging:
  level:
    org.springfromework.web: debug
    com.lysj.property: debug

---
spring:
  profiles: local
  flyway:
    out-of-order: true
  datasource:
    url: jdbc:postgresql://localhost:5432/property
    username: property
    password: 123456

---
spring:
  profiles: test
  flyway:
    out-of-order: false

---
spring:
  profiles: produce
  datasource:
    url: jdbc:postgresql://localhost:5432/property
    username: property
    password: 123456